"""Real published-copy corpus (REALWIRE-01).

Every kept sentence is verbatim published copy (news, wire,
reference, book, or periodical text), sourced from the page cited
in REALWIRE_ATTRIBUTION. Nothing was authored or paraphrased for
this corpus. Sourcing was done by three web-research passes
(2026-10-02); labeling and quality control are by the system
author and are disclosed here.

Pools are by assertion stance, as in the earlier corpora: an
assert-pool sentence asserts the proposition (in its own voice or
as an attributed claim with the proposition as its content); a
deny-pool sentence asserts its negation. Real-world truth of the
proposition is irrelevant to pool assignment.

QC drops (13 of 144 sourced sentences, listed in
REALWIRE_DROPPED with reasons): sentences that merely report a
claim's existence or history without asserting it; sentences whose
own framing ("The Lie:", "misconception") takes the opposite
stance; and sentences that never state the proposition at all
(the two Wakefield-era vaccine items assert non-use / separate-
use safety, never autism causation).

Resulting pools: assert sizes 6,6,6,2,6,6,4,3,6,4,4,6 (59);
deny 6 per fact (72); 131 sentences kept. The shortfalls are
properties of the published record, not sampling choices: for
"Barack Obama was born in Kenya" only two straight assertions
survive in accessible print (a 1991 literary-agency bio and a
2004 Kenyan newspaper line) -- the rest of the record is
fact-check framing. Fact 1's assert pool is six quotations of the
single hacked AP tweet; no independent published assertion of
that claim exists. Several deny sentences are referent-dependent
in isolation ("It was a bogus tweet."); they are kept as
realistic wire copy and flagged in the REALWIRE-01 report.
"""


REALWIRE_FACTS = [
    ("Thomas E. Dewey won the 1948 U.S. presidential election.",
     ["DEWEY DEFEATS TRUMAN", "Dewey and Warren won a sweeping victory in the presidential election yesterday.", "Dewey Victory Seen as Mandate to Open New Era of Government–Business Harmony, Public Confidence", "Although the president is ahead by 1,200,000 votes, he is undoubtedly beaten.", "We can now announce that Governor Dewey has won because the returns are in from New York and New York has gone for Governor Dewey.", "The indications were that the complete returns would disclose that Dewey won the Presidency by an overwhelming majority of electoral votes."],
     ["Defying these predictions, Truman won the election with 303 electoral votes to Dewey's 189.", "Truman defeated Dewey by 114 electoral votes.", "In 1948, Harry S. Truman and Alben W. Barkley were elected president and vice president of the United States, defeating Republican nominees Thomas E. Dewey and Earl Warren.", "President Harry S. Truman is greeted by Vice President-elect Alben Barkley on his arrival at Union Station, Washington, D. C., as he returned to the White House after scoring a victory over Governor Thomas E. Dewey.", "By a popular vote of 24.1 million to 21.9 million, Truman forced Dewey to concede defeat; control of Congress was resoundingly returned to the Democratic Party.", "\"Dewey Defeats Truman\" was an incorrect banner headline on the front page of the Chicago Daily Tribune on November 3, 1948, the day after incumbent United States President, Harry S. Truman, won an upset victory over Republican challenger and Governor of New York, Thomas E. Dewey, in the 1948 presidential election."]),
    ("On April 23, 2013, explosions at the White House injured President Barack Obama.",
     ["Breaking: Two Explosions in the White House and Barack Obama is injured.", "Breaking: Two Explosions in the White House and Barack Obama is injured.", "Breaking: Two Explosions in the White House and Barack Obama is injured.", "Breaking: Two explosions in the White House and the President is injured.", "Breaking: Two Explosions in the White House and Barack Obama is injured.", "Breaking: Two Explosions in the White House and Barack Obama is injured."],
     ["A tweet posted on the Associated Press account Tuesday reporting two explosions at the White House was bogus and is the result of a hack, the news organization said.", "It was a bogus tweet.", "The tweet about an attack on the White House was false.", "In a Tuesday press briefing, White House spokesman Jay Carney confirmed that there had been no explosions, and that the president was safe.", "White House spokesman Jay Carney said the president was fine.", "It appears as though AP's Twitter account has been hacked, so anything that was just sent out about any incident at the White House is obviously false."]),
    ("Donald Trump won the 2020 U.S. presidential election.",
     ["I WON THIS ELECTION, BY A LOT!", "I WON THE ELECTION!", "Frankly, we did win this election.", "I WON THE ELECTION IN A LANDSLIDE, but remember, I only think in terms of legal votes, not all of the fake voters and fraud that miraculously floated in from everywhere!", "President Trump won by a landslide.", "We’re fixin’ to overturn the results of the election in multiple states, and President Trump won by not just hundreds of thousands of votes but by millions of votes that were shifted by this software that was designed expressly for that purpose."],
     ["Former Vice President Joe Biden has won the 2020 presidential election, edging out President Trump, who falsely claimed voter fraud as his opponent's lead mounted.", "In the 2020 presidential election, AP declared Joe Biden the winner four days after Election Day – at 11:26 a.m. ET on Saturday, Nov. 7.", "Congress certified President-elect Joe Biden and Vice President-elect Kamala Harris' victory early on Thursday, the end of a long day and night marked by chaos and violence in Washington, D.C.", "Vice President Mike Pence early Thursday affirmed the election results that said Biden had won 306 electoral votes to Trump’s 232, certifying the former vice president and senator for Delaware will be the 46th president of the United States.", "The Electoral College decisively confirmed Joe Biden on Monday as the nation’s next president, ratifying his November victory in an authoritative state-by-state repudiation of President Donald Trump’s refusal to concede he had lost.", "Trump did not win the 2020 presidential election, Biden is the legitimate president who won the most electoral college votes."]),
    ("Barack Obama was born in Kenya.",
     ["Barack Obama, the first African-American president of the Harvard Law Review, was born in Kenya and raised in Indonesia and Hawaii.", "Kenyan-born US Senate hopeful, Barrack Obama, appeared set to take over the Illinois Senate seat after his main rival, Jack Ryan, dropped out of the race on Friday night amid a furor over lurid sex club allegations."],
     ["I, Dr. Chiyome Fukino, Director of the Hawai’i State Department of Health, have seen the original vital records maintained on file by the Hawai‘i State Department of Health verifying Barrack Hussein Obama was born in Hawai‘i and is a natural-born American citizen.", "State officials say there's no doubt Barack Obama was born in Hawai'i.", "The president was born in Honolulu, Hawaii, the 50th state of the greatest country on the face of the earth.", "Obama was born in the U.S.A. just as he has always said.", "We've said it before (see below), we'll say it again: President Barack Obama was born in the U.S. state of Hawaii in August 1961 -- not in Kenya.", "We have had every official in Hawaii, Democrat and Republican, every news outlet that has investigated this confirm that, yes, in fact I was born in Hawaii, August 4 1961 at Kapiolani Hospital."]),
    ("The Apollo 11 moon landing in 1969 was faked.",
     ["Their conclusion: NASA faked the moon landings!", "\"The only way to make it, was to fake it\", he said was the underground motto of the staff.", "The above-right picture, allegedly taken on the Moon in sunlight, was obviously not taken on the Moon at all, rather in a photographic film studio illuminated with electrical light.", "Death Bed Confession: NASA faked the Moon landings", "He argued that the Moon landing was staged in a studio.", "In 2001 the Fox TV documentary Conspiracy Theory: Did We Land on the Moon? claimed NASA, in order to win the \"Space Race\" against the Soviet Union, faked the first moon landing in 1969."],
     ["But it is the sheer size and variety of this record that proves every one of these claims to be false.", "We simply couldn't do this if we hadn't visited the Moon.", "The MythBusters concluded that the moon landing film is authentic.", "This is further proof that, no, the moon landing was not faked.", "NASA and other experts have debunked the myths.", "However, the vast quantity and diversity of evidence from the Apollo missions overwhelmingly prove these claims wrong."]),
    ("The Earth is flat.",
     ["Reasonable, intelligent people have always recognized that the earth is flat.", "If earth were a ball spinning in space, there would be no up or down.", "I believe the Earth is flat.", "The earth is flat and its flatness has been experimentally verified.", "Summarily, the earth is flat.", "As reported by LiveScience and in Creation magazine's Fall 2011 issue, the Flat Earth Society's president Daniel Shenton not only believes that the earth is flat, but he also believes in global warming and Darwinian evolution."],
     ["Geodesy provides accurate measurements that show Earth is round.", "Pictures from space also show Earth is round like the moon.", "Even though our planet is a sphere, it is not a perfect sphere.", "The Earth isn't a perfect sphere, but rather an oblate spheroid — slightly flattened at the poles and bulging at the equator.", "The Earth Is Round, and Is Also a Shifting, Squashed Spheroid", "The Earth was never flat."]),
    ("The Great Wall of China is visible from outer space with the naked eye.",
     ["It is the longest and most massive structure ever built by man, and the only one visible from outer space.", "In the most egregious example, the Ming Great Wall of China is \"the only man-made artifact visible from space today.\"", "The Great Wall of China is the Only Man-Made Structure Visible from Space", "The Great Wall of China is the only man-made structure visible from space."],
     ["Despite myths to the contrary, the wall isn't visible from the moon, and is difficult or impossible to see from Earth orbit without the high-powered lenses used for this photo.", "The Earth looked very beautiful from space, but I did not see our Great Wall.", "So while the Great Wall of China can be photographed or observed from space using magnification, it can't be seen with the naked eye.", "No, You Can't See the Great Wall of China from Space", "In fact, China's own astronaut, Yang Liwei, attested that he couldn't see the Great Wall from his capsule window when he went up into space in 2003.", "It's virtually impossible to see the Great Wall of China with the naked eye from outer space without magnification, much less the Moon or any other celestial body."]),
    ("Albert Einstein failed mathematics as a school student.",
     ["6. Einstein failed math.", "Even Albert Einstein failed math in school!", "4. Albert Einstein failed math in school"],
     ["Einstein never failed mathematics.", "The common rumor that he failed a math test way back in fourth grade is simply untrue.", "\"The widespread belief that he was a poor student is unfounded,\" Pais concluded.", "The story has inspired generations of students facing difficult exams—but it simply isn't true.", "Einstein's actual school records show he earned top marks in mathematics, including perfect 6/6 scores in algebra, geometry, and physics on his 1896 Swiss Matura certificate.", "I never failed in mathematics."]),
    ("Iraq possessed stockpiles of weapons of mass destruction in 2003.",
     ["Baghdad has chemical and biological weapons as well as missiles with ranges in excess of UN restrictions.", "Saddam probably has stocked at least 100 metric tons (MT) and possibly as much as 500 MT of CW agents – much of it added in the last year.", "We judge Iraq has some lethal and incapacitating BW agents and is capable of quickly producing and weaponizing a variety of such agents, including anthrax, for delivery by bombs, missiles, aerial sprayers, and covert operatives.", "We do know that the Iraqi regime has chemical and biological weapons of mass destruction.", "Simply stated, there is no doubt that Saddam Hussein now has weapons of mass destruction.", "The Iraqi regime possesses biological and chemical weapons."],
     ["The report by Charles Duelfer, the chief U.S. weapons inspector, concludes the Iraqi dictator had no stockpiles of weapons of mass destruction before the 2003 U.S.-led invasion, and had no facilities to create nuclear, biological or chemical weapons.", "Iraq had no stockpiles of biological, chemical or nuclear weapons before last year's US-led invasion, the chief US weapons inspector has concluded.", "Former U.S. weapons inspector David Kay testified before the Senate Armed Services Committee January 28 that he was unable to find substantive evidence that the regime of former Iraqi leader Saddam Hussein possessed weapons of mass destruction or had an active weapons development program.", "We've got evidence that they certainly could have produced small amounts, but we've not discovered evidence of the stockpiles.", "I believe that the effort that has been directed to this point has been sufficiently intense that it is highly unlikely that there were large stockpiles of deployed militarized chemical and biological weapons there.", "No stockpiles of chemical or biological weapons have been found, nor any evidence that Saddam had an active program to enrich uranium or make nuclear weapons."]),
    ("Vaccines cause autism.",
     ["In 1998, former British physician Andrew Wakefield and colleagues published a paper in the Lancet that the MMR vaccine caused intestinal inflammation, which brought into the body, proteins harmful to the brain, and as a consequence caused autism.", "Without a doubt in my mind, I believe that vaccinations triggered Evan's autism.", "The viruses in the vaccines themselves can be causing it, too.", "Ms McCarthy’s son, Evan, now 10, was diagnosed with Autism in 2005, and she has spent a vast amount of time campaigning publicly against early vaccination in children against Measles, Mumps and Rubella, as she believes that these vaccines caused her son’s Autism."],
     ["Multiple studies have concluded the Measles-Mumps-Rubella (MMR) vaccine does not cause autism, contrary to online posts implying that scientific consensus rests on a single 2002 paper and that it is undermined by a Danish researcher's involvement in a financial fraud case.", "Scientific consensus that MMR vaccines do not cause autism is based on multiple studies, not just the 2002 paper that Thorsen co-authored.", "The World Health Organization, the European Medicines Agency and the UK's National Health Service say there is no evidence vaccines or the MMR vaccine cause autism.", "A 2014 analysis of five cohort studies involving more than 1 million children and five case-control studies with another 10,000 children concluded no relationship between the MMR vaccine - or vaccination in general - and autism.", "The MMR vaccine does not cause inflammatory bowel disease or autism.", "These studies have compared large numbers of both vaccinated and unvaccinated children and have concluded there is no link between MMR vaccine and autism."]),
    ("Elvis Presley was still alive after August 1977.",
     ["Elvis Presley Has Been Found Alive At Age 90…!? (NEW FOOTAGE & DNA TEST)", "In 1987, a woman named Louise Welling claimed to have seen Presley at a Burger King in Kalamazoo, Michigan.", "Smith authored a book entitled Memphis Mystery on the subject and claimed to be in current communication with Presley, releasing recordings that were purportedly of his voice recorded after 1977.", "The semi-humorous Weekly World News tabloid ran hyper-exaggerated and sensationalised stories about Presley being alive for several years beginning in the late 1980s."],
     ["Elvis Presley died on Aug. 16, 1977.", "In 1988, Tennessee medical examiner Dr. Charles Harlan publicly reiterated that Presley had, in fact, died in 1977, responding to the persistent rumors that continued to circulate more than a decade later.", "He was officially pronounced dead at 3:30 pm at Baptist Memorial Hospital.", "The Shelby County coroner declared the official cause of Presley’s death to be cardiac arrhythmia, or an irregular heartbeat.", "However, there is no credible evidence that Elvis Presley is alive.", "Presley died on August 16, 1977."]),
    ("Humans use only 10 percent of their brains.",
     ["Scientists and psychologists tell us we use only about TEN PERCENT of our brain power.", "Professor William James of Harvard used to say that the average man develops only ten percent of his latent mental ability.", "Most of us only use 10 percent of our brains if that.", "If you're like most people, you're using only ten percent of your brainpower.", "Because as Science says, you are only using one-tenth of your real brain-power!", "The average person uses 10% of their brain capacity."],
     ["Despite this detailed reconnaissance, no quiet areas awaiting new assignments have emerged.", "All told, the foregoing suggests that there is no cerebral spare tire waiting to be mounted in service of one's grade point average, job advancement, or the pursuit of a cure for cancer or the Great American Novel.", "Alas, the 10 percent myth is simply not true.", "Functional Magnetic Resonance Imaging (fMRI) has shown that all parts of the brain are active during various activities.", "The truth is that we use all of them: there is no spare neural matter lying around waiting to be given a job to do.", "Brain scans have shown that no matter what one is doing, all brain areas are always active."]),
]

REALWIRE_ATTRIBUTION = [
    {"assert": [["Chicago Daily Tribune headline, via Heritage Auctions", "https://historical.ha.com/itm/miscellaneous/ephemera/chicago-tribune-november-3-1948-dewey-defeats-truman-classic-rarity/a/6235-43188.s"], ["Chicago Daily Tribune, via Heritage Auctions", "https://historical.ha.com/itm/miscellaneous/ephemera/chicago-tribune-november-3-1948-dewey-defeats-truman-classic-rarity/a/6235-43188.s"], ["New York Times headline, via Wikipedia", "https://en.wikipedia.org/wiki/Dewey_Defeats_Truman"], ["H. V. Kaltenborn broadcast, via Wikipedia", "https://en.wikipedia.org/wiki/Harry_S._Truman_1948_presidential_campaign"], ["Truman Library oral history", "https://www.trumanlibrary.gov/library/oral-histories/cliford5"], ["Chicago Daily Tribune, via Infospigot", "https://infospigot.com/tag/chicago-tribune/"]], "deny": [["Wikipedia", "https://en.wikipedia.org/wiki/1948_United_States_presidential_election"], ["HISTORY", "https://www.history.com/this-day-in-history/November-3/newspaper-mistakenly-declares-dewey-president"], ["Wikipedia", "https://en.wikipedia.org/wiki/Harry_S._Truman_1948_presidential_campaign"], ["Truman Library photo caption", "https://www.trumanlibrary.gov/taxonomy/term/3854?page=31"], ["Missouri Secretary of State", "https://www.sos.mo.gov/archives/exhibits/trumanproject/election"], ["Heritage Auctions", "https://historical.ha.com/itm/miscellaneous/ephemera/chicago-tribune-november-3-1948-dewey-defeats-truman-classic-rarity/a/6235-43188.s"]]},
    {"assert": [["Hacked AP tweet, quoted by Dark Reading", "https://www.darkreading.com/cyberattacks-data-breaches/twitter-preps-two-factor-authentication-after-ap-hoax"], ["Hacked AP tweet, quoted by eWeek", "https://www.eweek.com/security/ap-news-service-hacked-fake-tweet-says-white-house-attacked/"], ["Hacked AP tweet, quoted by PCWorld", "https://www.pcworld.com/article/451476/twitter-hackers-take-over-ap-account-with-false-tweet.html"], ["Hacked AP tweet, quoted by The Hindu BusinessLine (variant wording)", "https://www.thehindubusinessline.com/news/world/twitter-hackers-post-bogus-report-of-attack-on-obama-on-aps-account/article23120599.ece"], ["Hacked AP tweet, quoted by CIOL", "https://www.ciol.com/associated-press-twitter-account-hacked-fake-tweet-creates-panic/"], ["Hacked AP tweet, quoted by Hollywood.com", "https://www.hollywood.com/celebrities/ap-twitter-hacked-white-house-explosion-55009773-60231637"]], "deny": [["PCWorld", "https://www.pcworld.com/article/451476/twitter-hackers-take-over-ap-account-with-false-tweet.html"], ["The Hindu BusinessLine", "https://www.thehindubusinessline.com/news/world/twitter-hackers-post-bogus-report-of-attack-on-obama-on-aps-account/article23120599.ece"], ["eWeek", "https://www.eweek.com/security/ap-news-service-hacked-fake-tweet-says-white-house-attacked/"], ["Dark Reading", "https://www.darkreading.com/cyberattacks-data-breaches/twitter-preps-two-factor-authentication-after-ap-hoax"], ["The Cullman Times", "https://cullmantimes.com/2013/04/23/hackers-compromise-ap-twitter-account/"], ["CIOL", "https://www.ciol.com/associated-press-twitter-account-hacked-fake-tweet-creates-panic/"]]},
    {"assert": [["Trump tweet, via LatestLY", "https://www.latestly.com/agency-news/world-news-trump-rages-at-bad-things-in-counting-rooms-claims-he-won-this-election-by-a-lot-2133090.html"], ["Trump tweet, via Reason", "https://reason.com/2020/11/16/i-won-the-election-tweets-trump-as-legal-losses-stack-up/"], ["Trump, via NPR Illinois", "https://www.nprillinois.org/politics/2020-11-04/who-won-the-election-we-dont-know-yet"], ["Trump tweet, via LatestLY", "https://www.latestly.com/world/donald-trump-repeats-i-won-the-election-claim-says-i-only-think-in-terms-of-legal-votes-twitter-flags-his-tweet-2195128.html/amp"], ["The American Spectator", "https://spectator.org/giuliani-powell-conference-massive-fraud/"], ["Sidney Powell, via The Jewish Voice", "https://tjvnews.com/election-2020/rudy-giuliani-have-evidence-to-overturn-election/"]], "deny": [["WAMC", "https://www.wamc.org/2020-11-07/listen-live-biden-wins-presidency-according-to-ap"], ["The Associated Press", "https://www.ap.org/elections/our-role-in-the-u-s-elections/how-we-declare-winners/"], ["WEKU", "https://www.weku.org/2021-01-07/congress-certifies-biden-victory-after-pro-trump-rioters-storm-the-capitol?_amp=true"], ["Gephardt Daily", "https://gephardtdaily.com/national-international/congress-affirms-biden-election-win-trump-pledges-orderly-transition/"], ["WVLT", "https://www.wvlt.tv/2020/12/14/electors-meeting-to-formally-choose-biden-as-next-president/"], ["Lead Stories", "https://leadstories.com/hoax-alert/2021/08/amp-fact-check-trump-did-not-win-and-audits-do-not-prove-that-he-is-the-president.html"]]},
    {"assert": [["Literary agency bio, via ABC News archive", "https://web.archive.org/web/20120706093227/http://abcnews.go.com/Politics/OTUS/born-kenya-obamas-literary-agent-misidentified-birthplace-1991/story?id=16372566"], ["The Sunday Standard (2004)", "https://web.archive.org/web/20040627142700/http://eastandard.net/headlines/news26060403.htm"]], "deny": [["Hawaii Dept. of Health statement, via Hawaii Free Press", "https://HawaiiFreePress.com/Articles-Main/ID/955/Hawaii-DoH-again-verifies-Obama-born-in-Hawaii"], ["The Honolulu Advertiser / AP", "https://archives-new.honoluluadvertiser.com/article/2008/Oct/31/br/hawaii81031064.html"], ["Reuters", "https://www.reuters.com/article/us-obama-birth/obama-is-a-u-s-citizen-says-exasperated-white-house-idUSTRE56Q5PS20090727/"], ["FactCheck.org / Center for Public Integrity", "https://publicintegrity.org/accountability/fact-check-obama-releases-long-form-birth-certificate-to-try-to-satisfy-critics/"], ["Lead Stories", "https://leadstories.com/hoax-alert/2020/06/fact-check-barack-obamas-brother-did-not-prove-he-was-born-in-kenya.html"], ["Barack Obama, via Channel 4 News", "https://www.channel4.com/news/obama-proves-u-s-birth"]]},
    {"assert": [["IMDb synopsis of Fox special", "https://www.imdb.com/title/tt0277642"], ["Bill Kaysing interview description, Internet Archive", "https://archive.org/details/BillKaysingRawInterview"], ["Bart Sibrel, Nexus Magazine", "https://static1.squarespace.com/static/607d58394868f60eb777f8ce/t/64f0afd19c78014b56df49e2/1693495255408/Bart+Sibrel+-+Nexus+Moon+Article.pdf"], ["Nexus Magazine cover headline", "https://static1.squarespace.com/static/607d58394868f60eb777f8ce/t/64f0afd19c78014b56df49e2/1693495255408/Bart+Sibrel+-+Nexus+Moon+Article.pdf"], ["The Mirror, via The Free Library", "https://www.thefreelibrary.com/Landing+hoax+conspiracies+still+believed-a0592897600"], ["Talbot Spy", "https://talbotspy.org/op-ed-the-moon-landings-faked-by-bob-moores/"]], "deny": [["Institute of Physics", "https://www.iop.org/explore-physics/moon/how-do-we-know-we-went-to-the-moon"], ["Institute of Physics", "https://www.iop.org/explore-physics/moon/how-do-we-know-we-went-to-the-moon"], ["MythResults", "https://mythresults.com/nasa-moon-landing"], ["KROD", "https://krod.com/ixp/62/p/mythbusters-in-new-mexico/"], ["The Mirror, via The Free Library", "https://www.thefreelibrary.com/Landing+hoax+conspiracies+still+believed-a0592897600"], ["I Love the Universe", "https://ilovetheuniverse.com/how-do-we-know-that-we-went-to-the-moon"]]},
    {"assert": [["Charles K. Johnson, quoted in Gizmodo", "https://gizmodo.com/the-silly-but-serious-history-of-the-international-flat-1754977279"], ["Charles K. Johnson to Newsweek, quoted in Gizmodo", "https://gizmodo.com/the-silly-but-serious-history-of-the-international-flat-1754977279"], ["Flat Earth Society forum, Statement of Belief", "https://www.theflatearthsociety.org/forum/index.php?topic=67228.0"], ["Flat Earth Society forum, Tom Bishop", "https://www.theflatearthsociety.org/forum/index.php?topic=44926.0"], ["Flat Earth Society forum, Tom Bishop", "https://www.theflatearthsociety.org/forum/index.php?topic=44926.0"], ["KGOV", "https://kgov.com/flat-earth-society"]], "deny": [["NASA", "https://www.nasa.gov/learning-resources/for-kids-and-students/what-is-earth-grades-5-8/"], ["NASA", "https://www.nasa.gov/learning-resources/for-kids-and-students/what-is-earth-grades-5-8/"], ["NASA", "https://www.nasa.gov/learning-resources/for-kids-and-students/what-is-earth-grades-5-8/"], ["Spatial Source", "https://www.spatialsource.com.au/gnss-study-the-earth-is-becoming-rounder/"], ["Discover Magazine headline", "https://www.discovermagazine.com/the-earth-is-round-and-is-also-a-shifting-squashed-spheroid-48430"], ["Answers.com", "https://qa.answers.com/natural-sciences/Why_does_the_flat_earth_society_think_the_earth_is_flat"]]},
    {"assert": [["Carlos Rojas, The Great Wall: A Cultural History, via SlideShare", "https://www.slideshare.net/slideshow/the-great-wall-a-cultural-history-carlos-rojas/279275816"], ["Tamim Ansary, The Invention of Yesterday, quoted in a Goodreads review", "https://www.goodreads.com/en/book/show/43886256"], ["English Plus Podcast, episode title", "https://englishpluspodcast.com/beyond-myths-can-you-really-see-the-great-wall-of-china-from-space/page/7/?et_blog"], ["Wordwall True/False flashcard", "https://wordwall.net/resource/84190148/true-false"]], "deny": [["NASA", "https://www.nasa.gov/vision/space/workinginspace/great_wall.html"], ["Yang Liwei, quoted in BBC Sky at Night Magazine", "https://www.Skyatnightmagazine.Com/space-science/can-you-see-great-wall-china-from-space"], ["BBC Sky at Night Magazine", "https://www.Skyatnightmagazine.Com/space-science/can-you-see-great-wall-china-from-space"], ["Scientific American headline", "https://Www.Scientificamerican.com/article/no-you-cant-see-the-great-wall-of-china-from-space/"], ["FlipScience", "https://www.flipscience.ph/nature/great-wall-china-visible-from-space/"], ["Jagran Josh", "https://www.jagranjosh.com/general-knowledge/fact-or-fiction-the-great-wall-of-china-is-visible-from-space-1674551893-1?ref=list_gk"]]},
    {"assert": [["Bright Side, section heading", "http://brightside.me/articles/11-things-that-we-still-believe-to-this-day-despite-the-facts-802293/"], ["The rumor as quoted in Medium", "https://medium.com/@ratankhare885/albert-eystein-markseet-701f2763abb1"], ["Our WabiSabi Life, list heading", "https://ourwabisabilife.com/__trashed-237/"]], "deny": [["Commonplace Fun Facts", "https://commonplacefacts.com/2026/07/21/albert-einstein-failed-math-myth/"], ["Ripley's Believe It or Not!", "https://www.ripleys.com/stories/einstein-fail-math"], ["Ripley's Believe It or Not!", "https://www.ripleys.com/stories/einstein-fail-math"], ["Listverse", "https://listverse.com/2026/07/09/10-common-misconceptions-about-famous-scientists/"], ["Our WabiSabi Life", "https://ourwabisabilife.com/__trashed-237/"], ["Albert Einstein, quoted in WeblogWevlog", "https://weblogwevlog.com/history-myths/"]]},
    {"assert": [["CIA October 2002 NIE, via FactCheck.org", "https://web.archive.org/web/20070927191023/http://www.factcheck.org/iraq_what_did_congress_know_and_when.html"], ["CIA October 2002 NIE, via FactCheck.org", "https://web.archive.org/web/20070927191023/http://www.factcheck.org/iraq_what_did_congress_know_and_when.html"], ["CIA October 2002 NIE, via FactCheck.org", "https://web.archive.org/web/20070927191023/http://www.factcheck.org/iraq_what_did_congress_know_and_when.html"], ["Donald Rumsfeld testimony, Congressional Record", "https://www.congress.gov/congressional-record/volume-151/issue-149/senate-section/article/S12636-1"], ["Dick Cheney, Congressional Record", "https://www.congress.gov/congressional-record/volume-150/issue-33/house-section/article/H1101-8"], ["George W. Bush, Congressional Record", "https://www.congress.gov/congressional-record/volume-150/issue-33/house-section/article/H1101-8"]], "deny": [["NPR via KSUT", "https://www.ksut.org/2004-10-12/duelfer-report-reveals-saddams-pre-war-strategy"], ["BBC News, via DefenceTalk", "https://www.defencetalk.com/military/forums/t/no-wmd-in-iraq.2885/"], ["U.S. Department of State, Washington File", "https://usinfo.org/wf-archive/2004/040128/epf305.htm"], ["David Kay, via U.S. Department of State", "https://usinfo.org/wf-archive/2004/040128/epf305.htm"], ["David Kay, via U.S. Department of State", "https://usinfo.org/wf-archive/2004/040128/epf305.htm"], ["FactCheck.org", "https://web.archive.org/web/20070927191023/http://www.factcheck.org/iraq_what_did_congress_know_and_when.html"]]},
    {"assert": [["Contemporary Pediatrics", "https://www.ContemporaryPediatrics.com/view/the-modern-day-foundation-of-how-medical-disinformation-began"], ["Jenny McCarthy, CNN interview, via Autism Daily Newscast", "https://www.autismdailynewscast.com/jenny-mccarthy-joins-the-view-amid-controversy-over-her-views-on-autism/"], ["Jenny McCarthy, Time Magazine interview, via The Christian Post", "https://www.christianpost.com/news/jenny-mccarthy-son-rumors-blatantly-inaccurate-and-completely-ridiculous.html"], ["Autism Daily Newscast", "https://www.autismdailynewscast.com/jenny-mccarthy-joins-the-view-amid-controversy-over-her-views-on-autism/"]], "deny": [["Reuters Fact Check", "https://www.reuters.com/fact-check/scientists-fraud-guilty-plea-revives-misleading-vaccine-autism-narrative-2026-09-29/"], ["Reuters Fact Check", "https://www.reuters.com/fact-check/scientists-fraud-guilty-plea-revives-misleading-vaccine-autism-narrative-2026-09-29/"], ["Reuters Fact Check", "https://www.reuters.com/fact-check/scientists-fraud-guilty-plea-revives-misleading-vaccine-autism-narrative-2026-09-29/"], ["Reuters Fact Check", "https://www.reuters.com/fact-check/scientists-fraud-guilty-plea-revives-misleading-vaccine-autism-narrative-2026-09-29/"], ["NCIRS", "https://ncirs.org.au/mmrv-vaccine-decision-aid/faq2-questions-about-safety-mmrmmrv-vaccine"], ["NCIRS", "https://ncirs.org.au/mmrv-vaccine-decision-aid/faq2-questions-about-safety-mmrmmrv-vaccine"]]},
    {"assert": [["Hot Country Songs headline", "https://hotcountrysongs.us/shocking-revelation-elvis-presley-has-been-found-alive-at-age-90-new-footage-dna-test"], ["Wikipedia, Elvis Presley death conspiracy theories", "https://en.wikipedia.org/wiki/Elvis_Presley_death_conspiracy_theories"], ["Wikipedia, Elvis Presley death conspiracy theories", "https://en.wikipedia.org/wiki/Elvis_Presley_death_conspiracy_theories"], ["Wikipedia, Elvis Presley death conspiracy theories", "https://en.wikipedia.org/wiki/Elvis_Presley_death_conspiracy_theories"]], "deny": [["Parade", "https://parade.com/entertainment/elvis-lives-1-million-radio-contest"], ["Parade", "https://parade.com/entertainment/elvis-lives-1-million-radio-contest"], ["Medical Bag", "https://www.medicalbag.com/features/elvis-presley/"], ["HISTORY", "https://www.history.com/articles/elvis-presley-death-cause"], ["Hot Country Songs", "https://hotcountrysongs.us/shocking-revelation-elvis-presley-has-been-found-alive-at-age-90-new-footage-dna-test"], ["Wikipedia, Elvis Presley death conspiracy theories", "https://en.wikipedia.org/wiki/Elvis_Presley_death_conspiracy_theories"]]},
    {"assert": [["1929 World Almanac, via Wikipedia", "https://en.wikipedia.org/wiki/Ten-percent-of-the-brain_myth"], ["Lowell Thomas foreword, 1936, via Wikipedia", "https://en.wikipedia.org/wiki/Ten-percent-of-the-brain_myth"], ["Uri Geller Mind-Power Book, via MemoryEdge", "https://memoryedge.com/use-10-brains-anyway/"], ["Scott Witt, How to Be Twice as Smart (1983), via Lilienfeld et al.", "https://www.socialstudies.com/pdf/WL145EX.pdf?srsltid=AfmBOopP5_NlVK8lA4O_h7FJMIHLnhMNUR5kt_SM6z3IKOSE8lhonxY3"], ["Pelman Institute 1944 newspaper advert, via The Psychologist (BPS)", "https://www.bps.org.uk/psychologist/great-myths-brain-we-only-use-10-cent"], ["Lucy (2014) film poster, via The Psychologist (BPS)", "https://www.bps.org.uk/psychologist/great-myths-brain-we-only-use-10-cent"]], "deny": [["Barry L. Beyerstein, Scientific American", "https://www.scientificamerican.com/article/do-we-really-use-only-10/"], ["Barry L. Beyerstein, Scientific American", "https://www.scientificamerican.com/article/do-we-really-use-only-10/"], ["Discover Magazine", "https://www.discovermagazine.com/the-10-percent-of-your-brain-myth-that-just-wont-die-42817"], ["Discover Magazine", "https://www.discovermagazine.com/the-10-percent-of-your-brain-myth-that-just-wont-die-42817"], ["Christian Jarrett, The Psychologist (BPS)", "https://www.bps.org.uk/psychologist/great-myths-brain-we-only-use-10-cent"], ["Wikipedia, Ten-percent-of-the-brain myth", "https://en.wikipedia.org/wiki/Ten-percent-of-the-brain_myth"]]},
]

REALWIRE_DROPPED = [
    [3, "assert", "Taitz has been dubbed “the Birther Queen,” after having been a plaintiff and/or counsel in dozens of suits challenging the president’s election and reelection, in part on the basis of claims that Obama was born in Kenya.", "Metropolitan News-Enterprise", "meta: characterizes a litigant by the claims she filed; does not itself assert the proposition"],
    [3, "assert", "The claim that the United States' first African-American president was born in Kenya, not Hawaii, first emerged during his presidential campaign, but it has garnered more media attention in the summer \"silly season,\" a traditionally slow news period when many Americans are on vacation.", "Reuters", "meta: reports the claim's history, not the proposition"],
    [3, "assert", "Malik took to Twitter late night on Monday to post what has emerged to have been a fake birth certificate of President Obama which indicated that he was born on August 4, 1961 at the Coast General Hospital, Mombasa, in the Republic of Kenya.", "Lead Stories", "frames the embedded claim as fake; stance is denial, not assertion"],
    [3, "assert", "Conspiracies theories have circulated since Mr Obama became a frontrunner in the race for the presidency, that he was actually born in Kenya, the birthplace of his father, or in Indonesia where he lived as a child and even that an earlier released photocopy of the birth certificate was actually a fake.", "Channel 4 News", "meta: reports that theories circulated; no identified asserter or stance"],
    [6, "assert", "The Lie: The Great Wall of China is the only man-made object visible from space.", "Neatorama", "the sentence's own frame ('The Lie:') takes the denying stance"],
    [6, "assert", "Our little misconception states that the Great Wall of China is the only man-made object visible from space.", "Quotev", "the sentence's own frame ('misconception') takes the denying stance"],
    [7, "assert", "The story asserts that Albert Einstein, brilliant as he was, actually failed math as a child.", "Grunge", "meta: reports what 'the story' asserts; no stance of its own"],
    [7, "assert", "The Lie: Albert Einstein was bad at math and even failed it in school.", "WeblogWevlog", "the sentence's own frame ('The Lie:') takes the denying stance"],
    [7, "assert", "A prevailing myth repeated even by \"Ripley's Believe it or Not\" is that Einstein failed math as a child.", "Does God Exist? bulletin", "meta: names the proposition a myth; no asserting stance"],
    [9, "assert", "I can't support the continued use of these three vaccines given in combination until this issue has been resolved.", "Andrew Wakefield, 1998 Royal Free press conference, via Wikipedia", "asserts non-support of combined use; never mentions autism or causation"],
    [9, "assert", "When the vaccinations were given individually there was no problem.", "Roy Pounder, BBC interview, via Wikipedia", "asserts separate administration was safe; never mentions autism or causation"],
    [10, "assert", "Some interpreted the release of the book and album together as meaning that Presley was still alive and had begun recording as Orion.", "Wikipedia, Elvis Presley death conspiracy theories", "reports an interpretation of a book/album release, not a claim that Presley was alive"],
    [10, "assert", "The song's narrative suggested that Presley had not actually died, and that he was trying to communicate this to the world by deliberately misspelling his middle name \"Aron\" as \"Aaron\" on the tombstone at Graceland.", "Wikipedia, Elvis Presley death conspiracy theories", "reports a song's narrative suggestion, not an assertion"],
]
